updated comet setup
blend-capital/blend-utils pull request #24
Opened 2024-04-26 19:25 UTC by markuspluna

2024-04-26 19:37 UTC, mootz12 requested changes

2024-04-26 19:37 UTC, mootz12 commented on src/deploy/comet.ts
> +  await invokeSorobanOperation(cometFactory.init(comet_wasm), () => undefined, txParams);
Comet factory setup should be seperated no?

it feels like one script would be:

1. Deploy comet
-> install both contracts and call init on CometFactory

2. Deploy BLND_USDC Pool
 -> call newCometPool with the fixed params for a BLND-USDC pool (weights and swap fee hardcoded)
 -> intake blndAddress, usdcAddress, and balances as args

2024-04-26 21:31 UTC, Ryang-21 approved these changes

2024-04-30 18:43 UTC, mootz12 approved these changes

2024-04-30 18:43 UTC, merged